defaults:
  site_url: http://000000book.com
  host_name: 000000book.com
  mail_from: donotreply@000000book.com
  site_name: "#000000book"
  site_byline: "An open database for Graffiti Markup Language (GML) files"
  admin_email: admin@000000book.com

production:
  site_url: http://000000book.com
  # Google Analytics code goes below
  google_tracker_id:

test:
  site_url: http://fake.web
  host_name: localhost

development:
  site_url: http://localhost:3000
  host_name: localhost
