defaults:
  site_url: http://000000book.com
  host_name: 000000book.com
  mail_from: donotreply@000000book.com
  site_name: "#000000book"
  admin_email: admin@000000book.com
  blackbird: false
  # set this to automatically include the GA code in the footer, though you
  # probably only want to set it for production
  google_tracker_id:

production:
  site_url: http://000000book.com
  blackbird: false

test:
  blackbird: false

development:
  site_url: http://localhost:3000.com
  host_name: localhost